global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-services'
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'product-service:8080'
          - 'verification-service:8080'
          - 'event-service:8080'

rule_files:
  - /etc/prometheus/rules/alerting-rules.yaml
