# Production config (use env vars on Render)
spring.datasource.url=${POSTGRES_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Web3j config
web3j.client-address=${WEB3J_CLIENT_ADDRESS}
web3j.product-nft-contract-address=${PRODUCT_NFT_CONTRACT_ADDRESS}

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Actuator
management.endpoints.web.exposure.include=*
