import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';
import axios from 'axios';

const BASE = process.env.REACT_APP_API_BASE || '';
const Auth = createContext(null);
const useAuth = () => useContext(Auth);
const short = value => value ? `${value.slice(0, 12)}...${value.slice(-5)}` : '—';

function AuthProvider({ children }) {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('sp_user') || 'null'));
  const [token, setToken] = useState(() => localStorage.getItem('sp_token'));
  const complete = data => { setUser(data.user); setToken(data.accessToken); localStorage.setItem('sp_user', JSON.stringify(data.user)); localStorage.setItem('sp_token', data.accessToken); };
  const login = async (emailOrUsername, password) => complete((await axios.post(`${BASE}/auth/login`, { emailOrUsername, password })).data);
  const register = async payload => complete((await axios.post(`${BASE}/auth/register`, payload)).data);
  const logout = () => { setUser(null); setToken(null); localStorage.removeItem('sp_user'); localStorage.removeItem('sp_token'); };
  return <Auth.Provider value={{user, token, login, register, logout, authHeader: token ? {Authorization:`Bearer ${token}`} : {}}}>{children}</Auth.Provider>;
}
function Icon({name}) { const path={grid:'M3 3h7v7H3V3Zm11 0h7v7h-7V3ZM3 14h7v7H3v-7Zm11 0h7v7h-7v-7Z',plus:'M12 5v14M5 12h14',search:'m20 20-4.4-4.4m2.4-5.1a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z',vault:'M4 5h16v14H4V5Zm0 4h16M8 5v4m8-4v4',shield:'M12 3 20 6v5c0 5.1-3.4 8.7-8 10-4.6-1.3-8-4.9-8-10V6l8-3Zm-3.5 9 2.2 2.2 4.8-4.8',check:'m5 12 4.2 4.2L19 6.5',user:'M20 21a8 8 0 0 0-16 0m12-12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',logout:'M10 5H5v14h5m4-4 5-3-5-3m5 3H10'};return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={path[name]||path.grid}/></svg> }
const Button=({children,kind='primary',icon,...p})=><button className={`button button--${kind}`} {...p}>{icon&&<Icon name={icon}/>} {children}</button>;
const Status=({children,tone='good'})=><span className={`status status--${tone}`}><i/>{children}</span>;
const Data=({label,value})=><div><span>{label}</span><b>{value ?? '—'}</b></div>;

function Login({close}) { const {login,register}=useAuth();const [mode,setMode]=useState('login');const [f,setF]=useState({email:'',username:'',password:'',role:'MANUFACTURER'});const [error,setError]=useState('');const submit=async e=>{e.preventDefault();try{mode==='login'?await login(f.email,f.password):await register({email:f.email,username:f.username,password:f.password,displayName:f.username,role:f.role});close()}catch(x){setError(x.response?.data?.message||x.response?.data?.error||x.message)}};return <div className="modal-backdrop"><section className="auth-modal"><h2>{mode==='login'?'Enter the control room.':'Provision workspace.'}</h2>{error&&<div className="form-error">{error}</div>}<form className="auth-form" onSubmit={submit}>{mode==='register'&&<label>Operator name<input required onChange={e=>setF({...f,username:e.target.value})}/></label>}<label>Work email<input required type="email" onChange={e=>setF({...f,email:e.target.value})}/></label><label>Password<input required type="password" onChange={e=>setF({...f,password:e.target.value})}/></label>{mode==='register'&&<label>Access profile<select onChange={e=>setF({...f,role:e.target.value})}><option>MANUFACTURER</option><option>VERIFIER</option></select></label>}<Button type="submit">{mode==='login'?'Sign in securely':'Create workspace'}</Button></form><button className="text-button" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create an account':'Sign in'}</button></section></div> }
function Metrics({data}) { const rate=data?.verificationsToday?`${((1-data.failedVerificationsToday/data.verificationsToday)*100).toFixed(1)}%`:'—';return <section className="metrics-grid"><article className="metric"><p>PRODUCTS ATTESTED</p><strong>{data?.productsAttested??'—'}</strong></article><article className="metric"><p>ATTESTED TODAY</p><strong>{data?.productsAttestedToday??'—'}</strong></article><article className="metric"><p>VERIFICATION RATE</p><strong>{rate}</strong></article><article className="metric"><p>PENDING ATTESTATIONS</p><strong>{data?.pendingAttestations??'—'}</strong></article></section> }
function Activity({items}) { if(!items?.length)return <p className="panel-copy">No database events recorded yet.</p>;return <div className="activity-list">{items.map((item,i)=><div className="activity-row" key={`${item.productId}-${item.time}-${i}`}><span className={`activity-icon ${item.state==='REVIEW'?'activity-icon--bad':'activity-icon--good'}`}><Icon name={item.state==='REVIEW'?'shield':'check'}/></span><div><b>{item.action}</b><code>{item.productId}</code></div><time>{new Date(item.time).toLocaleString()}</time><Status tone={item.state==='REVIEW'?'danger':'good'}>{item.state}</Status></div>)}</div> }
function Dashboard({data,health,setView}) {return <div className="page-enter"><div className="page-heading"><div><span className="eyebrow">COMMAND CENTER / LIVE DATABASE</span><h1>Supply chain, <em>verified.</em></h1><p>All figures below are retrieved from PostgreSQL audit and provenance records.</p></div><Button icon="plus" onClick={()=>setView('enroll')}>Enroll item</Button></div><Metrics data={data}/><section className="dashboard-grid"><article className="panel chain-panel"><div className="panel__head"><div><span className="eyebrow">VERIFICATION FLOW</span><h2>Persistent provenance</h2></div><Status tone={health==='UP'?'good':'danger'}>{health==='UP'?'NOMINAL':'DEGRADED'}</Status></div><div className="chain-line"><div className="chain-node chain-node--active"><span>01</span><b>Physical capture</b><small>ONNX inference</small></div><div className="chain-link"/><div className="chain-node chain-node--active"><span>02</span><b>Vector match</b><small>PostgreSQL + pgvector</small></div><div className="chain-link"/><div className="chain-node"><span>03</span><b>Attestation</b><small>Transactional outbox</small></div></div></article><article className="panel integrity-panel"><span className="eyebrow">RISK POSTURE</span><h2>Failed checks today</h2><div className="integrity-score"><strong>{data?.failedVerificationsToday??'—'}</strong><span>events</span></div><p className="panel-copy">This is the persisted verification-audit count.</p></article></section><section className="panel activity-panel" style={{marginTop:19}}><span className="eyebrow">LIVE EVENT TAPE</span><h2>Recent activity</h2><Activity items={data?.recentActivity}/></section></div>}
function Capture({file,setFile}) {return <label className="capture-input">Physical product image<input required type="file" accept="image/jpeg,image/png" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>{file?file.name:'JPEG or PNG up to 10 MB. Server-side ONNX derives the fingerprint.'}</small></label>}
function Result({result,label}){const bad=!result.ok||result.data?.verified===false;return <section className={`result ${bad?'result--bad':'result--good'}`}><div className="result__head"><span className="result__icon"><Icon name={bad?'shield':'check'}/></span><div><span className="eyebrow">{label.toUpperCase()} RESPONSE</span><h2>{bad?'Identity was not confirmed':label==='Enrollment'?'Identity saved to database':'Product identity confirmed'}</h2></div></div>{!result.ok?<p>{result.msg}</p>:<div className="result__data"><Data label="Product ID" value={result.data.productId}/><Data label={label==='Enrollment'?'Feature hash':'Similarity'} value={label==='Enrollment'?short(result.data.featureHash):result.data.confidence?.toFixed(4)}/><Data label="Ledger status" value={result.data.blockchainConfirmed?'Confirmed':result.data.status||'Pending'}/></div>}</section>}
function Workflow({type,title,description,children}) {return <div className="page-enter workflow"><div className="page-heading"><div><span className="eyebrow">{type}</span><h1>{title}</h1><p>{description}</p></div></div><div className="workflow-grid"><section className="panel form-panel">{children}</section><aside className="workflow-aside"><div className="process-card"><span className="eyebrow">SECURE WORKFLOW</span><ol><li><i>01</i><div><b>Capture</b><span>Product image</span></div></li><li><i>02</i><div><b>Compute</b><span>ONNX fingerprint</span></div></li><li><i>03</i><div><b>Persist</b><span>PostgreSQL + ledger outbox</span></div></li></ol></div></aside></div></div>}
function CaptureFlow({verify,refresh}) {const {authHeader}=useAuth();const [id,setId]=useState('');const [meta,setMeta]=useState('');const [file,setFile]=useState(null);const [result,setResult]=useState(null);const [busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();if(!file)return;setBusy(true);try{const form=new FormData();form.append('productId',id);form.append('image',file);if(!verify&&meta)form.append('metadata',meta);const {data}=await axios.post(`${BASE}/api/${verify?'verify':'enroll'}/image`,form,{headers:authHeader});setResult({ok:true,data});refresh()}catch(x){setResult({ok:false,msg:x.response?.data?.error||x.response?.data?.message||x.message})}finally{setBusy(false)}};return <Workflow type={verify?'FIELD VERIFICATION / 03':'IDENTITY REGISTRY / 02'} title={verify?'Prove the product in hand.':'Enroll a physical identity.'} description="No client-side vectors or test data are generated. Each submission uses the supplied physical image."><form className="data-form" onSubmit={submit}><div className="form-section"><span>PRODUCT CONTEXT</span><label>Product identifier<input required value={id} onChange={e=>setId(e.target.value)} placeholder="e.g. PHARMA-LOT4892-2026"/></label><Capture file={file} setFile={setFile}/>{!verify&&<label>Metadata <em>OPTIONAL</em><textarea value={meta} onChange={e=>setMeta(e.target.value)} /></label>}</div><div className="form-actions"><Button disabled={busy} icon={verify?'search':'plus'}>{busy?'Processing physical capture…':verify?'Run verification':'Capture & enroll'}</Button></div></form>{result&&<Result result={result} label={verify?'Verification':'Enrollment'}/>}</Workflow>}
function Audit(){const {authHeader}=useAuth();const [id,setId]=useState('');const [r,setR]=useState(null);const go=async e=>{e.preventDefault();try{setR({ok:true,data:(await axios.get(`${BASE}/api/verify/${encodeURIComponent(id)}/log`,{headers:authHeader})).data})}catch(x){setR({ok:false,msg:x.response?.data?.error||x.message})}};return <div className="page-enter audit-page"><div className="page-heading"><div><span className="eyebrow">EVIDENCE VAULT / 04</span><h1>Retrieve the <em>record.</em></h1></div></div><section className="panel audit-search"><form onSubmit={go}><label>Search by product identifier<input required value={id} onChange={e=>setId(e.target.value)}/></label><Button icon="search">Query vault</Button></form></section>{r&&(r.ok?<section className="panel evidence-record"><h2>{r.data.productId}</h2><div className="evidence-grid"><Data label="Feature hash" value={short(r.data.featureHash)}/><Data label="Ledger block" value={r.data.blockNumber}/><Data label="Recorded" value={new Date(r.data.createdAt).toLocaleString()}/></div></section>:<section className="result result--bad"><p>{r.msg}</p></section>)}</div>}
function Shell(){const {user,logout,token}=useAuth();const [view,setView]=useState('dashboard');const [auth,setAuth]=useState(false);const [data,setData]=useState(null);const [health,setHealth]=useState('DOWN');const refresh=useCallback(async()=>{try{const headers=token?{Authorization:`Bearer ${token}`} : {};const [d,h]=await Promise.all([token?axios.get(`${BASE}/api/dashboard`,{headers}):Promise.resolve({data:null}),axios.get(`${BASE}/actuator/health`)]);setData(d.data);setHealth(h.data.status)}catch{setHealth('DOWN')}},[token]);useEffect(()=>{refresh();const i=setInterval(refresh,15000);return()=>clearInterval(i)},[refresh]);const nav=[['dashboard','Overview','grid'],['enroll','Enroll identity','plus'],['verify','Verify product','search'],['audit','Evidence vault','vault']];const pages={dashboard:<Dashboard data={data} health={health} setView={setView}/>,enroll:<CaptureFlow refresh={refresh}/>,verify:<CaptureFlow verify refresh={refresh}/>,audit:<Audit/>};return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand__mark"><span/><span/><span/></span><div><b>SupplyPrint</b><small>IDENTITY NETWORK</small></div></div><nav>{nav.map(n=><button key={n[0]} className={view===n[0]?'active':''} onClick={()=>setView(n[0])}><Icon name={n[2]}/><span>{n[1]}</span></button>)}</nav></aside><main><header className="topbar"><div className="crumb"><span>NETWORK</span><b>{nav.find(n=>n[0]===view)?.[1]}</b></div><div className="topbar__actions">{token?<div className="profile"><span>{(user?.displayName||user?.username||'O')[0]}</span><div><b>{user?.displayName||user?.username}</b><small>{user?.role}</small></div><button className="icon-button" onClick={logout}><Icon name="logout"/></button></div>:<Button kind="secondary" icon="user" onClick={()=>setAuth(true)}>Operator sign in</Button>}</div></header><div className="content">{pages[view]}</div></main>{auth&&<Login close={()=>setAuth(false)}/>}</div>}
export default function App(){return <AuthProvider><Shell/></AuthProvider>}
